---
title: "Manuscript Tables and Figures"
author: "Daniel Hocking"
date: "Friday, April 10, 2015"
output: html_document
---

```{r setup, echo=FALSE}
library(pander)
library(ggplot2)
library(dplyr)
library(RPostgreSQL)
library(lubridate)
library(conteStreamTemperature)
library(texreg)
library(stargazer)
#library(tables)

data_dir <- as.character(read.table("current_model_run.txt", stringsAsFactors = FALSE)[1,1])
local_dir <- data_dir

#df <- readRDS(file.path(data_dir, "obs_predicted.RData"))
coefs <- readRDS(file.path(data_dir, "coef.RData"))
covs <- readRDS(file.path(data_dir, "covariate_list.RData"))
df_breaks <- readRDS(file.path(data_dir, "springFallBPs.RData"))
df_rmse <- readRDS(file.path(data_dir, "rmse_table.RData"))
df_valid <- readRDS(file.path(data_dir, "valid_results.RData"))
rmse_tab <- readRDS(paste0(data_dir, "/RMSE_table.Rds"))
load(file.path(data_dir, "tempDataSync.RData"))
df_metrics <- readRDS(paste0(data_dir, "/derived_site_metrics.RData"))

df_breaks <- df_breaks %>%
  dplyr::mutate(featureid = as.character(site))

#df_temp <- left_join(df_temp, df_breaks, by = c("featureid", "year"))

df_stds
```


```{r presentation ggplot theme, echo=FALSE}
theme_bw_journal <- function (base_family = "") {
    theme_grey(base_family = base_family) %+replace% 
        theme(axis.text = element_text(size = rel(0.8)), axis.ticks = element_line(colour = "black"), 
            legend.key = element_rect(colour = "grey80"), panel.background = element_rect(fill = "white", 
                colour = NA), panel.border = element_rect(fill = NA, 
                colour = "grey50"), panel.grid.major = element_line(colour = "grey90", 
                size = 0.2), panel.grid.minor = element_line(colour = "grey98", 
                size = 0.5), strip.background = element_rect(fill = "grey80", 
                colour = "grey50", size = 0.2))
    }

theme_set(theme_bw_journal())
```

## Summary of data used

```{r temperature data summary, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
# str(tempDataSync)
# str(tempDataSyncValid)

agency_summary <- readRDS(paste0(data_dir, "/agency_summary.Rds"))
state_summary <- readRDS(paste0(data_dir, "/state_summary.Rds"))
data_totals <- readRDS(paste0(data_dir, "/data_totals.Rds"))

agency_summary <- dplyr::bind_rows(agency_summary, data_totals)
state_summary <- dplyr::bind_rows(state_summary, data_totals)
      
pandoc.table(format(agency_summary, 
                    digits = 1,
                    scientific = FALSE),
             justify = "right", 
             style = "rmarkdown", 
             split.table = Inf, 
             split.cells = c(1, 2, 2, 1, 2, 2))
      
pandoc.table(format(state_summary, 
                    digits = 1,
                    scientific = FALSE),
             justify = "right", 
             style = "rmarkdown", 
             split.table = Inf, 
             split.cells = c(1, 2, 2, 1, 2, 2))

```

We had data from `r nrow(state_summary) -1` and `r nrow(agency_summary)-1` organizations.

## Data used for fitting and validation

```{r data for fitting and validation, echo=FALSE, results='asis', message=FALSE, warning=FALSE}

# valid_results <- readRDS(file.path(data_dir, "valid_results.RData"))

fit_summary <- data.frame(Use = "Fit", Days = nrow(tempDataSyncS), Reaches =  length(unique(tempDataSyncS$featureid)), HUC8 =  length(unique(tempDataSyncS$huc)), Years =  length(unique(tempDataSyncS$year)), stringsAsFactors = FALSE)

valid_summary <- data.frame(Use = "Validate", Days = nrow(tempDataSyncValidS), Reaches =  length(unique(tempDataSyncValidS$featureid)), HUC8 =  length(unique(tempDataSyncValidS$huc)), Years =  length(unique(tempDataSyncValidS$year)), stringsAsFactors = FALSE)

data_summary <- dplyr::bind_rows(fit_summary, valid_summary)
data_summary

range(df_valid$year)
df_rmse
```

Validation Table

```{r validation table, echo=FALSE, results='asis', message=FALSE, warning=FALSE}

  pandoc.table(format(rmse_tab, 
                      digits = 2,
                      scientific = FALSE),
               justify = "right", 
               style = "rmarkdown",
               split.table = Inf)
```

Validation of derived metrics

```{r meanJuly validation, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
rmse(df_metrics$meanJulyObs - df_metrics$meanJulyTemp)

# number of reaches with sufficient observed data to calculate meanJulyObs
df_metrics %>%
  dplyr::filter(!is.na(meanJulyObs)) %>%
  nrow()

```

Coefficients

```{r coefficient table, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
df_foo <- coefs$fix.ef %>%
  dplyr::mutate(sig = ifelse(LCRI < 0 & 0 < UCRI, "", "*")) %>%
  dplyr::filter(coef != "B.huc_intercept.site", coef != "B.year_intercept.year") 

bar <- data.frame(coef = c("intercept"
                    , "B.huc_airTemp"
                    , "B.huc_temp7p"
                    , "prcp2"
                    , "prcp30"
                    , "AreaSqKM"
                    , "impoundArea"
                    , "forest"
                    , "agriculture"
                    , "devel_hi"
                    , "airTemp.prcp2"
                    , "airTemp.prcp30"
                    , "airTemp.da"
                    , "airTemp.impoundArea"
                    , "airTemp.forest"
                    , "airTemp.agriculture"
                    , "airTemp.devel_hi"
                    , "prcp2.da"
                    , "prcp30.da"
                    , "airTemp.prcp2.da"
                    , "airTemp.prcp30.da"
                    , "ar1"),
                  parameter = c("Intercept",
                              "AirT",
                              "7-day AirT",
                              "2-day Precip",
                              "30-day Precip",
                              "Drainage Area",
                              "Impounded Area",
                              "Riparian Forest Cover",
                              "Agriculture Cover",
                              "High Development Cover",
                              "AirT x 2-day Precip",
                              "AirT x 30-day Precip",
                              "AirT x Drainage",
                              "AirT x Impounded Area",
                              "AirT x Forest",
                              "AirT x Agriculture",
                              "AirT x High Development",
                              "2-day Precip x Drainage",
                              "30-day Precip x Drainage",
                              "AirT x 2-day Precip x Drainage",
                              "AirT x 30-day Precip x Drainage",
                              "AR1"),
                  stringsAsFactors = FALSE)
bar$row <- 1:nrow(bar)

df_foo <- df_foo %>%
  dplyr::left_join(bar) %>%
  dplyr::arrange(row) %>%
  dplyr::select(Parameter = parameter, Mean = mean, SD = sd, LCRI, UCRI)


pandoc.table(format(df_foo, 
                    digits = 1,
                    scientific = FALSE),
             justify = "right")

stargazer(df_foo, 
          title = "A.",
          summary=FALSE, 
          style = "apsr",
          rownames = F, 
          digits = 3, 
          type = "latex") # need to take the $ out of names if using stargazer


## Make table like lme4 results! ##
#random effects
coefs$sigma.site
ran.ef <- data.frame(rbind(coefs$sigma.site, coefs$sigma.huc, coefs$sigma.year), stringsAsFactors = FALSE) %>%
  dplyr::mutate(Variance = mean.sd^2)
ran.ef$Group <- c("Site", "", "", "HUC8", "", "", "Year")
ran.ef$Coef <- c("Intercept", "AirT", "7-day AirT", "Intercept", "AirT", "7-day AirT", "Intercept")
ran.ef <- dplyr::select(ran.ef, Group, Coef, SD = mean.sd, Variance)

stargazer(ran.ef, summary=FALSE, title = "", rownames = F, digits = 3, type = "latex")

pandoc.table(format(ran.ef, 
                    digits = 2,
                    scientific = FALSE),
             justify = "right")

coefs$cor.huc
ran.cor <- coefs$cor.huc
names(ran.cor) <- c("Intercept", "AirT", "7-day AirT")
row.names(ran.cor) <-  c("Intercept", "AirT", "7-day AirT")
stargazer(ran.cor, summary=FALSE, title = "", rownames = T, digits = 3, type = "latex")

pandoc.table(format(ran.cor, 
                    digits = 2,
                    scientific = FALSE),
             justify = "right",
             emphasize.rownames = FALSE)


stargazer(df_foo, ran.ef, 
          summary=FALSE,
          style = "apsr",
          dep.var.caption = "test",
          title = "", 
          rownames = F, 
          digits = 3, 
          type = "text")

```

## Derived metrics

```{r derived metrics definitions, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
metric_vec <- c("meanMaxTemp",
                "maxMaxTemp",
                "meanJulyTemp",
                "meanAugTemp",
                "meanSummerTemp",
                "mean30DayMax",
                "meanDays.18",
                "meanDays.22",
                "freqMaxTemp.18",
                "freqMaxTemp.22",
                "meanResist",
                "TS")

metric_names <- c("Mean maximum temperature",
                   "Max maximum temperature",
                   "Mean July temperature",
                   "Mean August temperature",
                   "Mean summer temperature",
                   "Mean 30-day maximum temperature",
                   "Mean number of days over 18 C",
                   "Mean number of days over 22 C",
                  "Annual frequency of exceeding 18 C",
                  "Annual frequency of exceeding 22 C",
                  "Mean annual resistance",
                  "Thermal sensitivity")

metric_descriptions <- c("Maximum daily mean water temperature (C) averaged over 36 years (1980 - 2015)",
                  "Maximum over years of the maximum daily mean temperature",
                  "Mean daily July temperature over years",
                  "Mean daily August temperature over years",
                  "Mean daily summer temperature over years",
                  "Maximum 30-day temperature for each year averaged over years",
                  "Mean number of days per year the mean daily temperature exceeds 18 C",
                  "Mean number of days per year the mean daily temperature exceeds 22 C",
                  "Frequency of years the mean daily temperature ever exceeds 18 C",
                  "Frequency of years the mean daily temperature ever exceeds 22 C",
                  "Mean annual resistance of water temperature to peak (summer) air temperature",
                  "Thermal sensitivity of water temperature to changes in air temperature")

metric_mean <- df_metrics %>%
  dplyr::select(one_of(metric_vec)) %>%
  dplyr::summarise_each(funs(mean(., na.rm = TRUE))) %>%
  t()

metric_min <- df_metrics %>%
  dplyr::select(one_of(metric_vec)) %>%
  dplyr::summarise_each(funs(min(., na.rm = TRUE))) %>%
  t()

metric_max <- df_metrics %>%
  dplyr::select(one_of(metric_vec)) %>%
  dplyr::summarise_each(funs(max(., na.rm = TRUE))) %>%
  t()

df_metric_summary_repo <- data.frame(Object = metric_vec, Short = metric_names, stringsAsFactors = FALSE)
  
df_metric_summary_repo <- df_metric_summary_repo %>%
  dplyr::bind_cols(as.data.frame(metric_mean)) %>%
  dplyr::bind_cols(as.data.frame(metric_min)) %>%
  dplyr::bind_cols(as.data.frame(metric_max)) %>%
  dplyr::bind_cols(as.data.frame(metric_descriptions))

colnames(df_metric_summary_repo) <- c("Object", "Metric", "Mean", "Min", "Max", "Description")

    pandoc.table(format(df_metric_summary_repo, 
                      digits = 2,
                      scientific = FALSE),
               justify = "right", 
               style = "rmarkdown",
               split.table = Inf)
    
  pandoc.table(format(dplyr::select(df_metric_summary_repo, -Object), 
                      digits = 2,
                      scientific = FALSE),
               justify = "right", 
               style = "rmarkdown",
               split.table = Inf)
```


```{r box plots and histograms of derived metrics}
metrics <- df_metrics %>%
  dplyr::select(mean30DayMax,
                freqMaxTemp.22,
                meanResist,
                TS)
g1 <- ggplot(metrics, aes(mean30DayMax)) + geom_histogram() + xlab("Annual 30-day maximum of mean daily temperature") + theme_bw_journal()
g2 <- ggplot(metrics, aes(freqMaxTemp.22)) + geom_histogram() + xlab("Frequency of years the max temperature exceeds 22 C") + theme_bw_journal()
g3 <- ggplot(metrics, aes(meanResist)) + geom_histogram() + xlab("Resistance to changes in summer air temperature") + theme_bw_journal()
g4 <- ggplot(metrics, aes(TS)) + geom_histogram() + xlab("Thermal sensitivity") + theme_bw_journal()

library(gridExtra)
#pdf(file = file.path("manuscripts/Figures", "metrics_histograms.jpg"), width = 12, height = 17, family = "Helvetica")
g <- grid.arrange(g1, g2, g3, g4, nrow = 2, ncol = 2)
#dev.off()
ggsave(filename = file.path("manuscripts/Figures", "metrics_histograms.jpg"), plot = g, device = "jpg")

```


Locations, Lat, Lon, Fitting, Validation, for Mapping Data Used

```{r locations for mapping data use}


```


